#!/usr/bin/env -S uv --quiet run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "tiktoken",
# ]
# ///

import tiktoken
import sys

enc = tiktoken.encoding_for_model("gpt-4o")
if len(sys.argv) < 2:
    input_text = sys.stdin.read()
else:
    with open(sys.argv[1]) as f:
        input_text = f.read()
encoded = enc.encode(input_text)
print(len(encoded))
