#!/usr/bin/env -S uv --quiet run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "mlx-whisper",
# ]
# ///

import sys
import mlx_whisper

model_path = "/Users/tm/models/mlx/whisper-large-v3-mlx"

for file in sys.argv[1:]:
    result = mlx_whisper.transcribe(file, path_or_hf_repo=model_path)
    base = file.rsplit('.', 1)[0]
    with open(base + '.txt', 'w') as f:
        f.write(result['text'])
